### PR TITLE
Buildfix for OpenGL ES2 build

### PR DESCRIPTION
**Pull request by rgabor-dev**
I'm not sure that these changes are correct so I need somebody to review.

### CODE REVIEW

**Comment by jeez** [comment]
@hugopl , we summon you. :)

**Comment by kalyankondapally** [comment]
Same with GLDefs change. Why do we need to include OpenGLShims for Gles??

**Comment by rgabor-dev** [comment]
It was necessary because GL_READ_FRAMEBUFFER and GL_READ_FRAMEBUFFER are missing from gl2ext.h and I don't know how to fix it properly. (it is needed at platform/graphics/opengl/GLPlatformSurface.cpp)
The other problem was glBlitFramebuffer() and with OpenGLShims.h I could solve this problem, thats why I used it.

**Comment by kalyankondapally** [comment]
k, there is no support for EXT_framebuffer_blit on GLES2, which defines all the needed attachment points for blitting.  Even though we might get it complied, it would cause run time issues.  I have some changes pending which should solve this for GraphicsSurface implementations. Would put it for review today eve or so.

**Comment by kalyankondapally** [comment]
k, there is no support for EXT_framebuffer_blit on GLES2, which defines all the needed attachment points for blitting.  Even though we might get it complied, it would cause run time issues.  I have some changes pending which should solve this for GraphicsSurface implementations. Would put it for review today eve or so.

**Comment by hugopl** [comment]
So I think is better to wait for kalyan patches, btw those add_definitions aren't needed, they should already exist in the generated cmakeconfig.h file.

**Comment by rgabor-dev** [comment]
Thanks Hugo, I see now how it works. I thought that these defines coming from the .cmake files. Anyway I agree with waiting for Kalyan patches and then just the Tools/WebKitTestRunner/nix/PlatformWebViewNix.cpp left to fix.

**Comment by jeez** [comment]
Do we need to keep this open?

**Comment by rgabor-dev** [comment]
I think we can close this. I will check later the status of the Opengl ES2 build.

**Pull request closed without merging**
