### PR TITLE
Enable full debug builds by having ar creating thin archives

### PR DESCRIPTION
**Pull request by spenap**
By default, CMake uses ar to generate libWebCore.a with cr parameters
(do not warn if the library has to be created, and replace existing
files in the archive). That results in a very large file, and ar fails
with sizes over 4GB.

By using thin archives (the T option of ar), the generated
libWebCore.a is much smaller, and can be successfully archived. As a
result, we can generate a full debug build. This patch is based on Xan
López's upstream webkit.org/b/110580.

### CODE REVIEW

**Comment by hugopl** [comment]
LGTM

**Comment by hugopl** [comment]
Can you push this patch on bugs.webkit.org? Or do you prefer to myself doing it on your behalf?

**Comment by spenap** [comment]
Sure, I will do that tomorrow. Cheers!

**Comment by spenap** [comment]
Hi Hugo, I just filed a bug with this patch in https://bugs.webkit.org/show_bug.cgi?id=125850

**Comment by hugopl** [comment]
So I'm closing the bug, thanks.

**Pull request closed without merging**
