### PR TITLE
Incorrect libsoup cache directory for WebProcess

### PR DESCRIPTION
**Pull request by elecro**
Now the cache dir is ~/.cache/ which isn't really cool... so this should fix it. for more info check #4.

### CODE REVIEW

**Comment by hugopl** [comment]
LGTM +1, I'll push the patch.

**Comment by hugopl** [comment]
I mean, I'll push because the "merge push request" button from github creates an unecessary  merge commit.

**Comment by elecro** [comment]
Cool, thanks.

**Comment by hugopl** [comment]
Pushed in commit a4a5157523fdd9a0ab6eecd83ee9280238770eac

**Pull request closed without merging**
