### PR TITLE
Enable libcurl as the network backend

### PR DESCRIPTION
**Pull request by elecro**
So this patch set will allow WebKitNix to be build with libcurl thus replacing libsoup as the network backend.

By default it will still be built with libsoup but there is a `ENABLE_SOUP` in the `FeaturesNix.config` file which if set to `0` will disable the libsoup and thus WebKit will be built with the libcurl.

### CODE REVIEW

**Comment by hugopl** [comment]
I have the dream of a having Nix free of glib in the future, do you think this is reasonable for libCurl backend?

I'm not saying to remove the GIO code now, I'm just asking if this would be possible without too much work in the future.

**Comment by balazs** [comment]
Definitely, I believe this an important motivation behind moving to libCurl. If I recall correctly it does not have any dependencies beside libc.

**Comment by hugopl** [comment]
Nice, my advice is: Don't worry with it (glib) right now, one step at a time :-)

**Comment by elecro** [comment]
At first I wanted to use simple socket calls (for the stream handler and the inspector server), but this was way faster :) . Only one thing is bit tricky and that is the handling the socket data in an async fashion (what the GIO does easly in this case)

**Comment by elecro** [comment]
So... can we go forward with this?

**Comment by hugopl** [comment]
Merged on commits: 6c6538ef965bf4ce51e86c2b657a046ea37e5e10 and b793fd33d862204b30bdc3663f09e397d43e60d5

**Comment by kromain** [comment]
Yay! Nice job guys, I'll use that as the baseline for my pull request adding WebSockets/InspectorServer support

**Pull request closed without merging**
